INSERT INTO NURSE(ID, FIRST_NAME ,LAST_NAME) values ( 1, 'Eigenia', 'Liashuk' );
INSERT INTO NURSE(ID, FIRST_NAME ,LAST_NAME) values ( 2, 'Ekaterina', 'Kozura' );
INSERT INTO NURSE(ID, FIRST_NAME ,LAST_NAME) values ( 3, 'Tatsiana', 'Rezko' );

INSERT INTO PATIENT(ID, FIRST_NAME, LAST_NAME, DIAGNOSIS, ILLNESS_DATE, NURSE_ID)
VALUES (1, 'Dzianis', 'Berastsen', 'Skalioz', '2021-10-01', 2 );
INSERT INTO PATIENT(ID, FIRST_NAME, LAST_NAME, DIAGNOSIS, ILLNESS_DATE, NURSE_ID)
VALUES (2, 'Kirill', 'Yrkovski', 'qwe', '2021-05-15', 1 );
INSERT INTO PATIENT(ID, FIRST_NAME, LAST_NAME, DIAGNOSIS, ILLNESS_DATE, NURSE_ID)
VALUES (3, 'Vladislav', 'Ivanov', 'xzc', '2021-01-29', 3 );
INSERT INTO PATIENT(ID, FIRST_NAME, LAST_NAME, DIAGNOSIS, ILLNESS_DATE, NURSE_ID)
VALUES (4, 'Valeriy', 'Sergeev', 'sdfg', '2021-05-15', 2 );

